import type { LanguageCode } from "./languageUtils";

// All UI string keys used across the app
export type UIStringKey =
  // Navigation
  | "nav.recyclingTool"
  | "nav.externalLinks"
  | "nav.menu"
  // RecyclingTools page
  | "recycling.title"
  | "recycling.intro.p1"
  | "recycling.intro.p2"
  | "recycling.intro.p3"
  | "recycling.intro.p4"
  | "recycling.filterSettings"
  // Search
  | "search.placeholder"
  // Filter modal
  | "filter.searchSettings"
  | "filter.close"
  | "filter.itemCategories"
  | "filter.rarity"
  | "filter.foundIn"
  | "filter.neededFor"
  | "filter.hasRecycleOutput"
  | "filter.hasRecycleDesc"
  | "filter.hasSalvageOutput"
  | "filter.hasSalvageDesc"
  | "filter.prioritizeNameMatches"
  | "filter.prioritizeNameDesc"
  | "filter.selectAll"
  | "filter.deselectAll"
  // Sort columns
  | "sort.name"
  | "sort.recyclesInto"
  | "sort.salvagesInto"
  | "sort.foundIn"
  | "sort.neededFor"
  | "sort.value"
  | "sort.sortByColumn"
  | "sort.sortBy"
  | "sort.ascending"
  | "sort.descending"
  | "sort.clearSort"
  // General
  | "general.total"
  | "general.noResults"
  | "general.close"
  | "general.scrollToTop"
  | "general.fieldCrafting"
  | "general.lastUpdated"
  // Needed-for source type labels (for filter display)
  | "source.hideout"
  | "source.quest"
  | "source.project"
  | "source.notNeeded"
  // Tooltip
  | "tooltip.hide"
  | "tooltip.show"
  // Error
  | "error.title"
  | "error.retry"
  | "error.copied"
  | "error.copyDetails"
  // Loading
  | "loading.message"
  // Requirement
  | "requirement.lvl"
  | "requirement.quest"
  | "requirement.step"
  // Category filter options (generated from ITEM_TYPES)
  | "category.ammunition"
  | "category.assaultrifle"
  | "category.augment"
  | "category.basicmaterial"
  | "category.battlerifle"
  | "category.blueprint"
  | "category.handcannon"
  | "category.key"
  | "category.lmg"
  | "category.misc"
  | "category.modification"
  | "category.nature"
  | "category.pistol"
  | "category.quickuse"
  | "category.recyclable"
  | "category.refinedmaterial"
  | "category.smg"
  | "category.shield"
  | "category.shotgun"
  | "category.sniperrifle"
  | "category.special"
  | "category.topsidematerial"
  | "category.trinket"
  // Rarity filter options
  | "rarity.common"
  | "rarity.uncommon"
  | "rarity.rare"
  | "rarity.epic"
  | "rarity.legendary"
  // Location filter options
  | "location.arc"
  | "location.commercial"
  | "location.electrical"
  | "location.exodus"
  | "location.industrial"
  | "location.mechanical"
  | "location.medical"
  | "location.nature"
  | "location.oldworld"
  | "location.residential"
  | "location.security"
  | "location.technological"
  | "location.nolocation";

// The translations record — English required, other languages optional
export const UI_STRINGS: Record<
  UIStringKey,
  Partial<Record<LanguageCode, string>> & { en: string }
> = {
  // Navigation
  "nav.recyclingTool": {
    en: "Recycling Tool",
    da: "Genbrugsværktøj",
    de: "Recycling-Werkzeug",
    es: "Herramienta de Reciclaje",
    fr: "Outil de Recyclage",
    he: "כלי מיחזור",
    hr: "Alat za recikliranje",
    it: "Strumento di Riciclaggio",
    ja: "リサイクルツール",
    "ko-KR": "재활용 도구",
    no: "Gjenbruksverktøy",
    pl: "Narzędzie Recyklingu",
    pt: "Ferramenta de Reciclagem",
    "pt-BR": "Ferramenta de Reciclagem",
    ru: "Инструмент переработки",
    sr: "Алат за рециклирање",
    tr: "Geri Dönüşüm Aracı",
    uk: "Інструмент переробки",
    "zh-CN": "回收工具",
    "zh-TW": "回收工具",
  },
  "nav.externalLinks": {
    en: "External Links",
    da: "Eksterne links",
    de: "Externe Links",
    es: "Enlaces externos",
    fr: "Liens externes",
    he: "קישורים חיצוניים",
    hr: "Vanjski linkovi",
    it: "Link esterni",
    ja: "外部リンク",
    "ko-KR": "외부 링크",
    no: "Eksterne lenker",
    pl: "Linki zewnętrzne",
    pt: "Links externos",
    "pt-BR": "Links externos",
    ru: "Внешние ссылки",
    sr: "Spoljni linkovi",
    tr: "Dış bağlantılar",
    uk: "Зовнішні посилання",
    "zh-CN": "外部链接",
    "zh-TW": "外部連結",
  },
  "nav.menu": {
    en: "Menu",
    da: "Menu",
    de: "Menü",
    es: "Menú",
    fr: "Menu",
    he: "תפריט",
    hr: "Izbornik",
    it: "Menu",
    ja: "メニュー",
    "ko-KR": "메뉴",
    no: "Meny",
    pl: "Menu",
    pt: "Menu",
    "pt-BR": "Menu",
    ru: "Меню",
    sr: "Мени",
    tr: "Menü",
    uk: "Меню",
    "zh-CN": "菜单",
    "zh-TW": "選單",
  },

  // RecyclingTools page
  "recycling.title": {
    en: "Recycling Tool",
    da: "Genbrugsværktøj",
    de: "Recycling-Werkzeug",
    es: "Herramienta de Reciclaje",
    fr: "Outil de Recyclage",
    he: "כלי מיחזור",
    hr: "Alat za recikliranje",
    it: "Strumento di Riciclaggio",
    ja: "リサイクルツール",
    "ko-KR": "재활용 도구",
    no: "Gjenbruksverktøy",
    pl: "Narzędzie Recyklingu",
    pt: "Ferramenta de Reciclagem",
    "pt-BR": "Ferramenta de Reciclagem",
    ru: "Инструмент переработки",
    sr: "Алат за рециклирање",
    tr: "Geri Dönüşüm Aracı",
    uk: "Інструмент переробки",
    "zh-CN": "回收工具",
    "zh-TW": "回收工具",
  },
  "recycling.intro.p1": {
    en: "Every item in Arc Raiders, laid out with its recycle and salvage outputs so you can figure out what to keep and what to break down without guessing.",
    da: "Alle genstande i Arc Raiders, vist med deres genbrugs- og salvageudbytte, så du kan finde ud af, hvad du skal beholde og hvad du skal nedbryde uden at gætte.",
    de: "Alle Gegenstände in Arc Raiders, mit ihren Recycling- und Salvage-Erträgen, damit Sie wissen, was Sie behalten und was Sie zerlegen sollten, ohne zu raten.",
    es: "Todos los objetos en Arc Raiders, mostrados con sus salidas de reciclaje y salvamento para que puedas decidir qué conservar y qué descomponer sin adivinar.",
    fr: "Tous les objets dans Arc Raiders, présentés avec leurs résultats de recyclage et de récupération pour que vous sachiez quoi garder et quoi démonter sans deviner.",
    he: "כל פריט ב-Arc Raiders, מוצג עם תוצאות המיחזור והפירוק שלו כדי שתוכל לדעת מה לשמור ומה לפרק בלי לנחש.",
    hr: "Svaka stavka u Arc Raidersu, prikazana sa svojim recikliranim i spašenim izlazima, tako da možete odlučiti što zadržati, a što rastaviti bez nagađanja.",
    it: "Ogni oggetto in Arc Raiders, mostrato con i suoi risultati di riciclaggio e recupero, così puoi capire cosa tenere e cosa smontare senza indovinare.",
    ja: "Arc Raidersのすべてのアイテムがリサイクルとサルベージの出力とともに表示され、何を保持し、何を分解するかを推測せずに判断できます。",
    "ko-KR":
      "Arc Raiders의 모든 아이템이 재활용 및 분해 결과와 함께 표시되어 무엇을 보관하고 무엇을 분해할지 추측하지 않고 결정할 수 있습니다.",
    no: "Alle gjenstander i Arc Raiders, vist med sine resirkulerings- og salvage-utganger, slik at du kan finne ut hva du skal beholde og hva du skal bryte ned uten å gjette.",
    pl: "Każdy przedmiot w Arc Raiders, pokazany z wynikami recyklingu i odzysku, dzięki czemu możesz zdecydować, co zachować, a co rozłożyć bez zgadywania.",
    pt: "Todos os itens em Arc Raiders, apresentados com seus resultados de reciclagem e salvamento para que você possa decidir o que manter e o que desmontar sem adivinhar.",
    "pt-BR":
      "Todos os itens em Arc Raiders, apresentados com seus resultados de reciclagem e salvamento para que você possa decidir o que manter e o que desmontar sem adivinhar.",
    ru: "Каждый предмет в Arc Raiders, представлен с результатами переработки и утилизации, чтобы вы могли понять, что сохранить, а что разобрать без догадок.",
    sr: "Svaka stavka u Arc Raidersu, prikazana sa svojim recikliranim i spašenim izlazima, tako da možete odlučiti šta zadržati, a šta rastaviti bez nagađanja.",
    tr: "Arc Raiders'daki her öğe, geri dönüşüm ve kurtarma çıktılarıyla birlikte sunuluyor, böylece neyi saklayıp neyi parçalayacağınızı tahmin etmeden anlayabilirsiniz.",
    uk: "Кожен предмет в Arc Raiders, показаний з результатами переробки та утилізації, щоб ви могли вирішити, що зберегти, а що розібрати без здогадок.",
    "zh-CN":
      "Arc Raiders中的每个物品都显示其回收和拆解结果，让你无需猜测即可决定保留什么和分解什么。",
    "zh-TW":
      "Arc Raiders中的每個物品都顯示其回收和拆解結果，讓你無需猜測即可決定保留什麼和分解什麼。",
  },
  "recycling.intro.p2": {
    en: "Search by item name, material, bench, project, or upgrade. The table highlights exactly what matched.",
    da: "Søg efter varenavn, materiale, bænk, projekt eller opgradering. Tabellen fremhæver præcis, hvad der matchede.",
    de: "Suche nach Gegenstandsname, Material, Bank, Projekt oder Upgrade. Die Tabelle hebt genau hervor, was übereinstimmt.",
    es: "Busca por nombre de objeto, material, banco, proyecto o mejora. La tabla resalta exactamente lo que coincidió.",
    fr: "Recherchez par nom d'objet, matériau, banc, projet ou amélioration. Le tableau met en évidence exactement ce qui a correspondu.",
    he: "חפש לפי שם פריט, חומר, ספסל, פרויקט או שדרוג. הטבלה מדגישה בדיוק מה התאים.",
    hr: "Pretražujte po nazivu stavke, materijalu, klupi, projektu ili nadogradnji. Tablica ističe točno ono što se podudara.",
    it: "Cerca per nome dell'oggetto, materiale, banco, progetto o upgrade. La tabella evidenzia esattamente ciò che corrisponde.",
    ja: "アイテム名、素材、ベンチ、プロジェクト、アップグレードで検索できます。テーブルは一致した内容を正確にハイライトします。",
    "ko-KR":
      "아이템 이름, 재료, 벤치, 프로젝트 또는 업그레이드로 검색하세요. 테이블은 정확히 일치한 항목을 강조 표시합니다.",
    no: "Søk etter varenavn, materiale, benk, prosjekt eller oppgradering. Tabellen fremhever nøyaktig hva som matchet.",
    pl: "Szukaj według nazwy przedmiotu, materiału, ławki, projektu lub ulepszenia. Tabela podkreśla dokładnie to, co pasowało.",
    pt: "Pesquise por nome do item, material, bancada, projeto ou upgrade. A tabela destaca exatamente o que correspondeu.",
    "pt-BR":
      "Pesquise por nome do item, material, bancada, projeto ou upgrade. A tabela destaca exatamente o que correspondeu.",
    ru: "Ищите по названию предмета, материалу, скамейке, проекту или улучшению. Таблица выделяет именно то, что совпало.",
    sr: "Pretražujte po nazivu stavke, materijalu, klupi, projektu ili nadogradnji. Tabela ističe tačno ono što se podudara.",
    tr: "Öğe adı, malzeme, tezgah, proje veya yükseltme ile arayın. Tablo tam olarak eşleşeni vurgular.",
    uk: "Шукайте за назвою предмета, матеріалом, лавкою, проектом чи оновленням. Таблиця виділяє саме те, що збіглося.",
    "zh-CN":
      "可按物品名称、材料、工作台、项目或升级搜索。表格会准确突出匹配项。",
    "zh-TW":
      "可按物品名稱、材料、工作台、項目或升級搜尋。表格會準確突出匹配項。",
  },
  "recycling.intro.p3": {
    en: "Filter by category to cut through the noise, and sort any column to find what you need.",
    da: "Filtrer efter kategori for at skære igennem støjen, og sorter enhver kolonne for at finde det, du har brug for.",
    de: "Filtern Sie nach Kategorie, um das Wesentliche zu finden, und sortieren Sie jede Spalte, um das zu finden, was Sie brauchen.",
    es: "Filtra por categoría para eliminar el ruido y ordena cualquier columna para encontrar lo que necesitas.",
    fr: "Filtrez par catégorie pour éliminer le bruit, et triez n'importe quelle colonne pour trouver ce dont vous avez besoin.",
    he: "סנן לפי קטגוריה כדי לחתוך את הרעש, ומיין כל עמודה כדי למצוא את מה שאתה צריך.",
    hr: "Filtrirajte po kategoriji kako biste uklonili šum, i sortirajte bilo koji stupac da pronađete što trebate.",
    it: "Filtra per categoria per eliminare il rumore e ordina qualsiasi colonna per trovare ciò di cui hai bisogno.",
    ja: "カテゴリで絞り込み、任意の列を並べ替えて必要なものを見つけましょう。",
    "ko-KR":
      "카테고리별로 필터링하고, 원하는 항목을 찾기 위해 모든 열을 정렬하세요.",
    no: "Filtrer etter kategori for å kutte gjennom støyen, og sorter hvilken som helst kolonne for å finne det du trenger.",
    pl: "Filtruj według kategorii, aby przebić się przez szum, i sortuj dowolną kolumnę, aby znaleźć to, czego potrzebujesz.",
    pt: "Filtre por categoria para eliminar o ruído e classifique qualquer coluna para encontrar o que precisa.",
    "pt-BR":
      "Filtre por categoria para eliminar o ruído e classifique qualquer coluna para encontrar o que precisa.",
    ru: "Фильтруйте по категории, чтобы избавиться от лишнего, и сортируйте любую колонку, чтобы найти нужное.",
    sr: "Filtrirajte po kategoriji da biste uklonili šum, i sortirajte bilo koji stupac da pronađete šta vam treba.",
    tr: "Kategorilere göre filtreleyin ve ihtiyacınızı bulmak için herhangi bir sütunu sıralayın.",
    uk: "Фільтруйте за категорією, щоб відсіяти зайве, і сортуйте будь-яку колонку, щоб знайти потрібне.",
    "zh-CN": "按类别筛选以消除杂音，并排序任意列以找到所需内容。",
    "zh-TW": "按類別篩選以消除雜音，並排序任意列以找到所需內容。",
  },
  "recycling.intro.p4": {
    en: "The Needed For column tracks hideout upgrades, quests, and project requirements so nothing gets recycled by accident.",
    da: "Kolonnen 'Bruges til' sporer skjulested-opgraderinger, quests og projektkrav, så intet bliver genbrugt ved et uheld.",
    de: "Die Spalte 'Benötigt für' verfolgt Versteck-Upgrades, Quests und Projektanforderungen, damit nichts versehentlich recycelt wird.",
    es: "La columna 'Necesario para' rastrea mejoras de escondite, misiones y requisitos de proyectos para que nada se recicle por accidente.",
    fr: "La colonne 'Nécessaire pour' suit les améliorations du refuge, les quêtes et les exigences des projets afin que rien ne soit recyclé par accident.",
    he: "עמודת 'נדרש עבור' עוקבת אחר שדרוגי מחבוא, משימות ודרישות פרויקטים כדי ששום דבר לא ימחזר בטעות.",
    hr: "Stupac 'Potrebno za' prati nadogradnje skloništa, zadatke i zahtjeve projekata kako ništa ne bi bilo reciklirano slučajno.",
    it: "La colonna 'Necessario per' tiene traccia degli upgrade del nascondiglio, delle missioni e dei requisiti dei progetti così nulla viene riciclato per errore.",
    ja: "必要列は隠れ家のアップグレード、クエスト、プロジェクト要件を追跡し、誤ってリサイクルされないようにします。",
    "ko-KR":
      "필요한 항목 열은 은신처 업그레이드, 퀘스트 및 프로젝트 요구 사항을 추적하여 실수로 재활용되는 일이 없도록 합니다.",
    no: "Kolonnen 'Trengs til' sporer oppgraderinger av skjulested, oppdrag og prosjektkrav, slik at ingenting blir resirkulert ved et uhell.",
    pl: "Kolumna 'Potrzebne do' śledzi ulepszenia kryjówki, zadania i wymagania projektów, dzięki czemu nic nie zostanie poddane recyklingowi przez pomyłkę.",
    pt: "A coluna 'Necessário para' rastreia upgrades de esconderijo, missões e requisitos de projetos para que nada seja reciclado por acidente.",
    "pt-BR":
      "A coluna 'Necessário para' rastreia upgrades de esconderijo, missões e requisitos de projetos para que nada seja reciclado por acidente.",
    ru: "Колонка 'Необходимо для' отслеживает улучшения убежища, задания и требования проектов, чтобы ничего не было переработано случайно.",
    sr: "Kolona 'Potrebno za' prati nadogradnje skloništa, zadatke i zahteve projekata kako ništa ne bi bilo reciklirano slučajno.",
    tr: "Gerekli olduğu sütun, sığınak yükseltmeleri, görevler ve proje gereksinimlerini takip eder, böylece hiçbir şey yanlışlıkla geri dönüştürülmez.",
    uk: "Стовпчик 'Потрібно для' відстежує оновлення сховища, завдання та вимоги проектів, щоб нічого не було перероблено випадково.",
    "zh-CN":
      "“所需”列会追踪藏身处升级、任务和项目需求，确保不会误回收任何物品。",
    "zh-TW":
      "「所需」欄會追蹤藏身處升級、任務和項目需求，確保不會誤回收任何物品。",
  },
  "recycling.filterSettings": {
    en: "Filter settings",
    da: "Filterindstillinger",
    de: "Filtereinstellungen",
    es: "Configuración de filtro",
    fr: "Paramètres de filtre",
    he: "הגדרות סינון",
    hr: "Postavke filtra",
    it: "Impostazioni filtro",
    ja: "フィルター設定",
    "ko-KR": "필터 설정",
    no: "Filterinnstillinger",
    pl: "Ustawienia filtra",
    pt: "Configurações de filtro",
    "pt-BR": "Configurações de filtro",
    ru: "Настройки фильтра",
    sr: "Podešavanja filtera",
    tr: "Filtre ayarları",
    uk: "Налаштування фільтра",
    "zh-CN": "筛选设置",
    "zh-TW": "篩選設定",
  },

  // Search
  "search.placeholder": {
    en: "Search items...",
    da: "Søg efter genstande...",
    de: "Gegenstände suchen...",
    es: "Buscar objetos...",
    fr: "Rechercher des objets...",
    he: "חפש פריטים...",
    hr: "Pretraži stavke...",
    it: "Cerca oggetti...",
    ja: "アイテム検索...",
    "ko-KR": "아이템 검색...",
    no: "Søk etter gjenstander...",
    pl: "Szukaj przedmiotów...",
    pt: "Pesquisar itens...",
    "pt-BR": "Pesquisar itens...",
    ru: "Поиск предметов...",
    sr: "Pretraži stavke...",
    tr: "Öğeleri ara...",
    uk: "Пошук предметів...",
    "zh-CN": "搜索物品...",
    "zh-TW": "搜尋物品...",
  },

  // Filter modal
  "filter.searchSettings": {
    en: "Search Settings",
    da: "Søgeindstillinger",
    de: "Sucheinstellungen",
    es: "Configuración de búsqueda",
    fr: "Paramètres de recherche",
    he: "הגדרות חיפוש",
    hr: "Postavke pretraživanja",
    it: "Impostazioni di ricerca",
    ja: "検索設定",
    "ko-KR": "검색 설정",
    no: "Søkeinnstillinger",
    pl: "Ustawienia wyszukiwania",
    pt: "Configurações de pesquisa",
    "pt-BR": "Configurações de pesquisa",
    ru: "Настройки поиска",
    sr: "Podešavanja pretrage",
    tr: "Arama ayarları",
    uk: "Налаштування пошуку",
    "zh-CN": "搜索设置",
    "zh-TW": "搜尋設定",
  },
  "filter.close": {
    en: "Close",
    da: "Luk",
    de: "Schließen",
    es: "Cerrar",
    fr: "Fermer",
    he: "סגור",
    hr: "Zatvori",
    it: "Chiudi",
    ja: "閉じる",
    "ko-KR": "닫기",
    no: "Lukk",
    pl: "Zamknij",
    pt: "Fechar",
    "pt-BR": "Fechar",
    ru: "Закрыть",
    sr: "Zatvori",
    tr: "Kapat",
    uk: "Закрити",
    "zh-CN": "关闭",
    "zh-TW": "關閉",
  },
  "filter.itemCategories": {
    en: "Item Categories",
    da: "Varekategorier",
    de: "Gegenstandskategorien",
    es: "Categorías de objetos",
    fr: "Catégories d'objets",
    he: "קטגוריות פריטים",
    hr: "Kategorije predmeta",
    it: "Categorie di oggetti",
    ja: "アイテムカテゴリ",
    "ko-KR": "아이템 분류",
    no: "Varekategorier",
    pl: "Kategorie przedmiotów",
    pt: "Categorias de itens",
    "pt-BR": "Categorias de itens",
    ru: "Категории предметов",
    sr: "Kategorije predmeta",
    tr: "Öğe kategorileri",
    uk: "Категорії предметів",
    "zh-CN": "物品类别",
    "zh-TW": "物品類別",
  },
  "filter.rarity": {
    en: "Rarity",
    da: "Sjældenhed",
    de: "Seltenheit",
    es: "Rareza",
    fr: "Rareté",
    he: "נדירות",
    hr: "Rijetkost",
    it: "Rarità",
    ja: "レアリティ",
    "ko-KR": "희귀도",
    no: "Sjeldenhet",
    pl: "Rzadkość",
    pt: "Raridade",
    "pt-BR": "Raridade",
    ru: "Редкость",
    sr: "Retkost",
    tr: "Nadirlik",
    uk: "Рідкість",
    "zh-CN": "稀有度",
    "zh-TW": "稀有度",
  },
  "filter.foundIn": {
    en: "Found In",
    da: "Fundet i",
    de: "Gefunden in",
    es: "Encontrado en",
    fr: "Trouvé dans",
    he: "נמצא ב",
    hr: "Pronađeno u",
    it: "Trovato in",
    ja: "入手場所",
    "ko-KR": "획득 위치",
    no: "Funnet i",
    pl: "Znalezione w",
    pt: "Encontrado em",
    "pt-BR": "Encontrado em",
    ru: "Найдено в",
    sr: "Pronađeno u",
    tr: "Bulunduğu yer",
    uk: "Знайдено в",
    "zh-CN": "发现于",
    "zh-TW": "發現於",
  },
  "filter.neededFor": {
    en: "Needed For",
    da: "Bruges til",
    de: "Benötigt für",
    es: "Necesario para",
    fr: "Nécessaire pour",
    he: "נדרש עבור",
    hr: "Potrebno za",
    it: "Necessario per",
    ja: "必要用途",
    "ko-KR": "필요 용도",
    no: "Trengs til",
    pl: "Potrzebne do",
    pt: "Necessário para",
    "pt-BR": "Necessário para",
    ru: "Необходимо для",
    sr: "Potrebno za",
    tr: "Gerekli olduğu",
    uk: "Потрібно для",
    "zh-CN": "所需用途",
    "zh-TW": "所需用途",
  },
  "filter.hasRecycleOutput": {
    en: "Has Recycle Output",
    da: "Har genbrugsudbytte",
    de: "Hat Recycling-Ertrag",
    es: "Tiene salida de reciclaje",
    fr: "A un résultat de recyclage",
    he: "יש תוצאת מיחזור",
    hr: "Ima reciklirani izlaz",
    it: "Ha risultato di riciclaggio",
    ja: "リサイクル結果あり",
    "ko-KR": "재활용 결과 있음",
    no: "Har resirkuleringsutbytte",
    pl: "Ma wynik recyklingu",
    pt: "Tem resultado de reciclagem",
    "pt-BR": "Tem resultado de reciclagem",
    ru: "Есть результат переработки",
    sr: "Ima reciklirani izlaz",
    tr: "Geri dönüşüm çıktısı var",
    uk: "Є результат переробки",
    "zh-CN": "有回收产物",
    "zh-TW": "有回收產物",
  },
  "filter.hasRecycleDesc": {
    en: "Only show items that produce materials when recycled.",
    da: "Vis kun genstande, der giver materialer ved genbrug.",
    de: "Nur Gegenstände anzeigen, die beim Recyceln Materialien erzeugen.",
    es: "Mostrar solo objetos que produzcan materiales al reciclarse.",
    fr: "Afficher uniquement les objets produisant des matériaux lors du recyclage.",
    he: "הצג רק פריטים שמניבים חומרים בעת מיחזור.",
    hr: "Prikaži samo predmete koji daju materijale pri recikliranju.",
    it: "Mostra solo oggetti che producono materiali quando riciclati.",
    ja: "リサイクル時に素材を生み出すアイテムのみ表示",
    "ko-KR": "재활용 시 재료를 생성하는 아이템만 표시",
    no: "Vis kun gjenstander som gir materialer ved resirkulering.",
    pl: "Pokaż tylko przedmioty, które dają materiały po recyklingu.",
    pt: "Mostrar apenas itens que produzem materiais ao serem reciclados.",
    "pt-BR": "Mostrar apenas itens que produzem materiais ao serem reciclados.",
    ru: "Показывать только предметы, которые дают материалы при переработке.",
    sr: "Prikaži samo predmete koji daju materijale pri reciklaži.",
    tr: "Yalnızca geri dönüşümde malzeme üretenleri göster",
    uk: "Показувати лише предмети, що дають матеріали при переробці.",
    "zh-CN": "仅显示回收时产生材料的物品。",
    "zh-TW": "僅顯示回收時產生材料的物品。",
  },
  "filter.hasSalvageOutput": {
    en: "Has Salvage Output",
    da: "Har salvage-udbytte",
    de: "Hat Salvage-Ertrag",
    es: "Tiene salida de salvamento",
    fr: "A un résultat de récupération",
    he: "יש תוצאת פירוק",
    hr: "Ima spašeni izlaz",
    it: "Ha risultato di recupero",
    ja: "サルベージ結果あり",
    "ko-KR": "분해 결과 있음",
    no: "Har salvage-utbytte",
    pl: "Ma wynik odzysku",
    pt: "Tem resultado de salvamento",
    "pt-BR": "Tem resultado de salvamento",
    ru: "Есть результат утилизации",
    sr: "Ima spašeni izlaz",
    tr: "Kurtarma çıktısı var",
    uk: "Є результат утилізації",
    "zh-CN": "有拆解产物",
    "zh-TW": "有拆解產物",
  },
  "filter.hasSalvageDesc": {
    en: "Only show items that produce materials when salvaged.",
    da: "Vis kun genstande, der giver materialer ved salvage.",
    de: "Nur Gegenstände anzeigen, die beim Salvagen Materialien erzeugen.",
    es: "Mostrar solo objetos que produzcan materiales al ser salvados.",
    fr: "Afficher uniquement les objets produisant des matériaux lors du sauvetage.",
    he: "הצג רק פריטים שמניבים חומרים בעת פירוק.",
    hr: "Prikaži samo predmete koji daju materijale pri spašavanju.",
    it: "Mostra solo oggetti che producono materiali quando recuperati.",
    ja: "サルベージ時に素材を生み出すアイテムのみ表示",
    "ko-KR": "분해 시 재료를 생성하는 아이템만 표시",
    no: "Vis kun gjenstander som gir materialer ved salvage.",
    pl: "Pokaż tylko przedmioty, które dają materiały po odzysku.",
    pt: "Mostrar apenas itens que produzem materiais ao serem salvos.",
    "pt-BR": "Mostrar apenas itens que produzem materiais ao serem salvos.",
    ru: "Показывать только предметы, которые дают материалы при утилизации.",
    sr: "Prikaži samo predmete koji daju materijale pri spašavanju.",
    tr: "Yalnızca kurtarmada malzeme üretenleri göster",
    uk: "Показувати лише предмети, що дають матеріали при утилізації.",
    "zh-CN": "仅显示拆解时产生材料的物品。",
    "zh-TW": "僅顯示拆解時產生材料的物品。",
  },
  "filter.prioritizeNameMatches": {
    en: "Prioritize name matches",
    da: "Prioriter navnematch",
    de: "Namensübereinstimmungen priorisieren",
    es: "Priorizar coincidencias de nombre",
    fr: "Prioriser les correspondances de nom",
    he: "העדף התאמות שם",
    hr: "Daj prednost podudaranju imena",
    it: "Dai priorità alle corrispondenze di nome",
    ja: "名前一致を優先",
    "ko-KR": "이름 일치 우선",
    no: "Prioriter navnetreff",
    pl: "Priorytet dla zgodności nazw",
    pt: "Priorizar correspondências de nome",
    "pt-BR": "Priorizar correspondências de nome",
    ru: "Приоритет совпадения имени",
    sr: "Daj prednost podudaranju imena",
    tr: "İsim eşleşmelerini önceliklendir",
    uk: "Пріоритет збігів імені",
    "zh-CN": "优先名称匹配",
    "zh-TW": "優先名稱匹配",
  },
  "filter.prioritizeNameDesc": {
    en: "When searching, items matching by name appear first regardless of sort column.",
    da: "Ved søgning vises genstande med navnematch først uanset sorteringskolonne.",
    de: "Beim Suchen erscheinen Gegenstände mit Namensübereinstimmung zuerst, unabhängig von der Sortierspalte.",
    es: "Al buscar, los objetos que coincidan por nombre aparecen primero sin importar la columna de orden.",
    fr: "Lors de la recherche, les objets correspondant par nom apparaissent en premier, quelle que soit la colonne de tri.",
    he: "בחיפוש, פריטים שתואמים בשם יופיעו ראשונים ללא קשר לעמודת המיון.",
    hr: "Pri pretraživanju, stavke koje se podudaraju po imenu pojavljuju se prve bez obzira na stupac sortiranja.",
    it: "Durante la ricerca, gli oggetti che corrispondono per nome appaiono per primi indipendentemente dalla colonna di ordinamento.",
    ja: "検索時、名前が一致するアイテムは並べ替え列に関係なく最初に表示されます。",
    "ko-KR":
      "검색 시 이름이 일치하는 항목이 정렬 열과 상관없이 먼저 표시됩니다.",
    no: "Ved søk vises elementer med navnetreff først uansett sorteringskolonne.",
    pl: "Podczas wyszukiwania elementy zgodne z nazwą pojawiają się najpierw, niezależnie od kolumny sortowania.",
    pt: "Ao pesquisar, itens que correspondem pelo nome aparecem primeiro, independentemente da coluna de ordenação.",
    "pt-BR":
      "Ao pesquisar, itens que correspondem pelo nome aparecem primeiro, independentemente da coluna de ordenação.",
    ru: "При поиске элементы, совпадающие по имени, появляются первыми независимо от столбца сортировки.",
    sr: "Pri pretrazi, stavke koje se podudaraju po imenu pojavljuju se prve bez obzira na kolonu sortiranja.",
    tr: "Aramada, isme uyanlar sıralama sütunundan bağımsız olarak önce gelir.",
    uk: "Під час пошуку елементи, що збігаються за іменем, з'являються першими незалежно від стовпця сортування.",
    "zh-CN": "搜索时，名称匹配的物品会优先显示，无论排序列如何。",
    "zh-TW": "搜尋時，名稱匹配的物品會優先顯示，無論排序欄如何。",
  },
  "filter.selectAll": {
    en: "Select All",
    da: "Vælg alle",
    de: "Alle auswählen",
    es: "Seleccionar todo",
    fr: "Tout sélectionner",
    he: "בחר הכל",
    hr: "Odaberi sve",
    it: "Seleziona tutto",
    ja: "すべて選択",
    "ko-KR": "모두 선택",
    no: "Velg alle",
    pl: "Zaznacz wszystko",
    pt: "Selecionar tudo",
    "pt-BR": "Selecionar tudo",
    ru: "Выбрать все",
    sr: "Odaberi sve",
    tr: "Tümünü seç",
    uk: "Вибрати все",
    "zh-CN": "全选",
    "zh-TW": "全選",
  },
  "filter.deselectAll": {
    en: "Deselect All",
    da: "Fravælg alle",
    de: "Alle abwählen",
    es: "Deseleccionar todo",
    fr: "Tout désélectionner",
    he: "בטל בחירה מהכל",
    hr: "Poništi odabir svega",
    it: "Deseleziona tutto",
    ja: "すべて選択解除",
    "ko-KR": "모두 선택 해제",
    no: "Fjern alle valg",
    pl: "Odznacz wszystko",
    pt: "Desmarcar tudo",
    "pt-BR": "Desmarcar tudo",
    ru: "Снять выделение со всего",
    sr: "Poništi odabir svega",
    tr: "Tümünü kaldır",
    uk: "Скасувати вибір усіх",
    "zh-CN": "取消全选",
    "zh-TW": "取消全選",
  },

  // Sort columns
  "sort.name": {
    en: "Name",
    da: "Navn",
    de: "Name",
    es: "Nombre",
    fr: "Nom",
    he: "שם",
    hr: "Ime",
    it: "Nome",
    ja: "名前",
    "ko-KR": "이름",
    no: "Navn",
    pl: "Nazwa",
    pt: "Nome",
    "pt-BR": "Nome",
    ru: "Имя",
    sr: "Ime",
    tr: "İsim",
    uk: "Ім'я",
    "zh-CN": "名称",
    "zh-TW": "名稱",
  },
  "sort.recyclesInto": {
    en: "Recycles Into",
    da: "Genbruges til",
    de: "Recycelt zu",
    es: "Recicla en",
    fr: "Recycle en",
    he: "ממחזר ל",
    hr: "Reciklira u",
    it: "Ricicla in",
    ja: "リサイクル結果",
    "ko-KR": "재활용 결과",
    no: "Resirkuleres til",
    pl: "Recyklinguje się w",
    pt: "Recicla em",
    "pt-BR": "Recicla em",
    ru: "Перерабатывается в",
    sr: "Reciklira u",
    tr: "Geri dönüşüm sonucu",
    uk: "Переробляється в",
    "zh-CN": "回收产物",
    "zh-TW": "回收產物",
  },
  "sort.salvagesInto": {
    en: "Salvages Into",
    da: "Salvageres til",
    de: "Bergt zu",
    es: "Salvaje en",
    fr: "Récupère en",
    he: "מחלץ ל",
    hr: "Spašava u",
    it: "Salvaguarda in",
    ja: "サルベージ結果",
    "ko-KR": "분해 결과",
    no: "Salvageres til",
    pl: "Odzyskuje się w",
    pt: "Salvage em",
    "pt-BR": "Salvage em",
    ru: "Утилизируется в",
    sr: "Spašava u",
    tr: "Kurtarma sonucu",
    uk: "Утилізується в",
    "zh-CN": "拆解产物",
    "zh-TW": "拆解產物",
  },
  "sort.foundIn": {
    en: "Found In",
    da: "Fundet i",
    de: "Gefunden in",
    es: "Encontrado en",
    fr: "Trouvé dans",
    he: "נמצא ב",
    hr: "Pronađeno u",
    it: "Trovato in",
    ja: "入手場所",
    "ko-KR": "획득 위치",
    no: "Funnet i",
    pl: "Znalezione w",
    pt: "Encontrado em",
    "pt-BR": "Encontrado em",
    ru: "Найдено в",
    sr: "Pronađeno u",
    tr: "Bulunduğu yer",
    uk: "Знайдено в",
    "zh-CN": "发现于",
    "zh-TW": "發現於",
  },
  "sort.neededFor": {
    en: "Needed For",
    da: "Bruges til",
    de: "Benötigt für",
    es: "Necesario para",
    fr: "Nécessaire pour",
    he: "נדרש עבור",
    hr: "Potrebno za",
    it: "Necessario per",
    ja: "必要用途",
    "ko-KR": "필요 용도",
    no: "Trengs til",
    pl: "Potrzebne do",
    pt: "Necessário para",
    "pt-BR": "Necessário para",
    ru: "Необходимо для",
    sr: "Potrebno za",
    tr: "Gerekli olduğu",
    uk: "Потрібно для",
    "zh-CN": "所需用途",
    "zh-TW": "所需用途",
  },
  "sort.value": {
    en: "Value",
    da: "Værdi",
    de: "Wert",
    es: "Valor",
    fr: "Valeur",
    he: "ערך",
    hr: "Vrijednost",
    it: "Valore",
    ja: "価値",
    "ko-KR": "가치",
    no: "Verdi",
    pl: "Wartość",
    pt: "Valor",
    "pt-BR": "Valor",
    ru: "Ценность",
    sr: "Vrednost",
    tr: "Değer",
    uk: "Цінність",
    "zh-CN": "价值",
    "zh-TW": "價值",
  },
  "sort.sortByColumn": {
    en: "Sort by column",
    da: "Sorter efter kolonne",
    de: "Nach Spalte sortieren",
    es: "Ordenar por columna",
    fr: "Trier par colonne",
    he: "מיין לפי עמודה",
    hr: "Sortiraj po stupcu",
    it: "Ordina per colonna",
    ja: "列で並べ替え",
    "ko-KR": "열로 정렬",
    no: "Sorter etter kolonne",
    pl: "Sortuj według kolumny",
    pt: "Ordenar por coluna",
    "pt-BR": "Ordenar por coluna",
    ru: "Сортировать по столбцу",
    sr: "Sortiraj po koloni",
    tr: "Sütuna göre sırala",
    uk: "Сортувати за стовпцем",
    "zh-CN": "按列排序",
    "zh-TW": "按欄排序",
  },
  "sort.sortBy": {
    en: "Sort by:",
    da: "Sorter efter:",
    de: "Sortieren nach:",
    es: "Ordenar por:",
    fr: "Trier par :",
    he: "מיין לפי:",
    hr: "Sortiraj po:",
    it: "Ordina per:",
    ja: "並べ替え基準：",
    "ko-KR": "정렬 기준:",
    no: "Sorter etter:",
    pl: "Sortuj według:",
    pt: "Ordenar por:",
    "pt-BR": "Ordenar por:",
    ru: "Сортировать по:",
    sr: "Sortiraj po:",
    tr: "Sırala:",
    uk: "Сортувати за:",
    "zh-CN": "排序依据：",
    "zh-TW": "排序依據：",
  },
  "sort.ascending": {
    en: "Sort ascending",
    da: "Sorter stigende",
    de: "Aufsteigend sortieren",
    es: "Orden ascendente",
    fr: "Tri croissant",
    he: "מיין עולה",
    hr: "Sortiraj uzlazno",
    it: "Ordina in modo crescente",
    ja: "昇順で並べ替え",
    "ko-KR": "오름차순 정렬",
    no: "Sorter stigende",
    pl: "Sortuj rosnąco",
    pt: "Ordenar crescente",
    "pt-BR": "Ordenar crescente",
    ru: "Сортировать по возрастанию",
    sr: "Sortiraj uzlazno",
    tr: "Artan sırala",
    uk: "Сортувати за зростанням",
    "zh-CN": "升序排序",
    "zh-TW": "升序排序",
  },
  "sort.descending": {
    en: "Sort descending",
    da: "Sorter faldende",
    de: "Absteigend sortieren",
    es: "Orden descendente",
    fr: "Tri décroissant",
    he: "מיין יורד",
    hr: "Sortiraj silazno",
    it: "Ordina in modo decrescente",
    ja: "降順で並べ替え",
    "ko-KR": "내림차순 정렬",
    no: "Sorter fallende",
    pl: "Sortuj malejąco",
    pt: "Ordenar decrescente",
    "pt-BR": "Ordenar decrescente",
    ru: "Сортировать по убыванию",
    sr: "Sortiraj silazno",
    tr: "Azalan sırala",
    uk: "Сортувати за спаданням",
    "zh-CN": "降序排序",
    "zh-TW": "降序排序",
  },
  "sort.clearSort": {
    en: "Clear sort",
    da: "Ryd sortering",
    de: "Sortierung löschen",
    es: "Limpiar orden",
    fr: "Effacer le tri",
    he: "נקה מיון",
    hr: "Očisti sortiranje",
    it: "Cancella ordinamento",
    ja: "並べ替え解除",
    "ko-KR": "정렬 해제",
    no: "Fjern sortering",
    pl: "Wyczyść sortowanie",
    pt: "Limpar ordenação",
    "pt-BR": "Limpar ordenação",
    ru: "Очистить сортировку",
    sr: "Očisti sortiranje",
    tr: "Sıralamayı temizle",
    uk: "Очистити сортування",
    "zh-CN": "清除排序",
    "zh-TW": "清除排序",
  },

  // General
  "general.total": {
    en: "Total:",
    da: "I alt:",
    de: "Gesamt:",
    es: "Total:",
    fr: "Total :",
    he: 'סה"כ:',
    hr: "Ukupno:",
    it: "Totale:",
    ja: "合計：",
    "ko-KR": "총계:",
    no: "Totalt:",
    pl: "Suma:",
    pt: "Total:",
    "pt-BR": "Total:",
    ru: "Всего:",
    sr: "Ukupno:",
    tr: "Toplam:",
    uk: "Всього:",
    "zh-CN": "总计：",
    "zh-TW": "總計：",
  },
  "general.noResults": {
    en: "No items found matching",
    da: "Ingen elementer fundet, der matcher",
    de: "Keine passenden Elemente gefunden",
    es: "No se encontraron elementos coincidentes",
    fr: "Aucun élément correspondant trouvé",
    he: "לא נמצאו פריטים תואמים",
    hr: "Nema pronađenih stavki koje odgovaraju",
    it: "Nessun elemento trovato corrispondente",
    ja: "一致するアイテムが見つかりません",
    "ko-KR": "일치하는 항목이 없습니다",
    no: "Ingen elementer funnet som samsvarer",
    pl: "Nie znaleziono pasujących elementów",
    pt: "Nenhum item correspondente encontrado",
    "pt-BR": "Nenhum item correspondente encontrado",
    ru: "Совпадающих элементов не найдено",
    sr: "Nema pronađenih stavki koje odgovaraju",
    tr: "Eşleşen öğe bulunamadı",
    uk: "Не знайдено відповідних елементів",
    "zh-CN": "未找到匹配的物品",
    "zh-TW": "未找到匹配的物品",
  },
  "general.close": {
    en: "Close",
    da: "Luk",
    de: "Schließen",
    es: "Cerrar",
    fr: "Fermer",
    he: "סגור",
    hr: "Zatvori",
    it: "Chiudi",
    ja: "閉じる",
    "ko-KR": "닫기",
    no: "Lukk",
    pl: "Zamknij",
    pt: "Fechar",
    "pt-BR": "Fechar",
    ru: "Закрыть",
    sr: "Zatvori",
    tr: "Kapat",
    uk: "Закрити",
    "zh-CN": "关闭",
    "zh-TW": "關閉",
  },
  "general.scrollToTop": {
    en: "Scroll to top",
    da: "Rul til toppen",
    de: "Nach oben scrollen",
    es: "Desplazar hacia arriba",
    fr: "Faire défiler vers le haut",
    he: "גלול למעלה",
    hr: "Pomakni na vrh",
    it: "Scorri in alto",
    ja: "トップへスクロール",
    "ko-KR": "맨 위로 스크롤",
    no: "Rull til toppen",
    pl: "Przewiń do góry",
    pt: "Rolar para o topo",
    "pt-BR": "Rolar para o topo",
    ru: "Прокрутить вверх",
    sr: "Pomeri na vrh",
    tr: "Yukarı kaydır",
    uk: "Прокрутити вгору",
    "zh-CN": "滚动到顶部",
    "zh-TW": "滾動到頂部",
  },
  "general.fieldCrafting": {
    en: "Crafting",
    da: "Håndværk",
    de: "Handwerk",
    es: "Artesanía",
    fr: "Artisanat",
    he: "מלאכה",
    hr: "Izrada",
    it: "Creazione",
    ja: "クラフト",
    "ko-KR": "제작",
    no: "Håndverk",
    pl: "Rzemiosło",
    pt: "Artesanato",
    "pt-BR": "Artesanato",
    ru: "Ремесло",
    sr: "Izrada",
    tr: "Zanaat",
    uk: "Ремесло",
    "zh-CN": "制作",
    "zh-TW": "製作",
  },
  "general.lastUpdated": {
    en: "Last Updated:",
    da: "Sidst opdateret:",
    de: "Zuletzt aktualisiert:",
    es: "Última actualización:",
    fr: "Dernière mise à jour :",
    he: "עודכן לאחרונה:",
    hr: "Zadnje ažurirano:",
    it: "Ultimo aggiornamento:",
    ja: "最終更新：",
    "ko-KR": "마지막 업데이트:",
    no: "Sist oppdatert:",
    pl: "Ostatnia aktualizacja:",
    pt: "Última atualização:",
    "pt-BR": "Última atualização:",
    ru: "Последнее обновление:",
    sr: "Zadnje ažurirano:",
    tr: "Son güncelleme:",
    uk: "Останнє оновлення:",
    "zh-CN": "最后更新：",
    "zh-TW": "最後更新：",
  },

  // Needed-for source type labels
  "source.hideout": {
    en: "Hideout",
    da: "Skjulested",
    de: "Versteck",
    es: "Escondite",
    fr: "Planque",
    he: "מסתור",
    hr: "Sklonište",
    it: "Nascondiglio",
    ja: "隠れ家",
    "ko-KR": "은신처",
    no: "Skjulested",
    pl: "Kryjówka",
    pt: "Esconderijo",
    "pt-BR": "Esconderijo",
    ru: "Убежище",
    sr: "Sklonište",
    tr: "Sığınak",
    uk: "Сховище",
    "zh-CN": "藏身处",
    "zh-TW": "藏身處",
  },
  "source.quest": {
    en: "Quest",
    da: "Quest",
    de: "Quest",
    es: "Misión",
    fr: "Quête",
    he: "משימה",
    hr: "Zadatak",
    it: "Missione",
    ja: "クエスト",
    "ko-KR": "퀘스트",
    no: "Oppdrag",
    pl: "Zadanie",
    pt: "Missão",
    "pt-BR": "Missão",
    ru: "Задание",
    sr: "Zadatak",
    tr: "Görev",
    uk: "Завдання",
    "zh-CN": "任务",
    "zh-TW": "任務",
  },
  "source.project": {
    en: "Project",
    da: "Projekt",
    de: "Projekt",
    es: "Proyecto",
    fr: "Projet",
    he: "פרויקט",
    hr: "Projekt",
    it: "Progetto",
    ja: "プロジェクト",
    "ko-KR": "프로젝트",
    no: "Prosjekt",
    pl: "Projekt",
    pt: "Projeto",
    "pt-BR": "Projeto",
    ru: "Проект",
    sr: "Projekat",
    tr: "Proje",
    uk: "Проєкт",
    "zh-CN": "项目",
    "zh-TW": "項目",
  },
  "source.notNeeded": {
    en: "Not Needed",
    da: "Ikke nødvendig",
    de: "Nicht benötigt",
    es: "No necesario",
    fr: "Non nécessaire",
    he: "לא נדרש",
    hr: "Nije potrebno",
    it: "Non necessario",
    ja: "不要",
    "ko-KR": "필요 없음",
    no: "Ikke nødvendig",
    pl: "Niepotrzebne",
    pt: "Não necessário",
    "pt-BR": "Não necessário",
    ru: "Не требуется",
    sr: "Nije potrebno",
    tr: "Gerekli değil",
    uk: "Не потрібно",
    "zh-CN": "不需要",
    "zh-TW": "不需要",
  },

  // Tooltip
  "tooltip.hide": {
    en: "Hide tooltip",
    da: "Skjul værktøjstip",
    de: "Tooltip ausblenden",
    es: "Ocultar información sobre herramientas",
    fr: "Masquer l'infobulle",
    he: "הסתר תיאור כלי",
    hr: "Sakrij opis alata",
    it: "Nascondi suggerimento",
    ja: "ツールチップを隠す",
    "ko-KR": "툴팁 숨기기",
    no: "Skjul verktøytips",
    pl: "Ukryj podpowiedź",
    pt: "Ocultar dica de ferramenta",
    "pt-BR": "Ocultar dica de ferramenta",
    ru: "Скрыть подсказку",
    sr: "Sakrij opis alata",
    tr: "Araç ipucunu gizle",
    uk: "Сховати підказку",
    "zh-CN": "隐藏工具提示",
    "zh-TW": "隱藏工具提示",
  },
  "tooltip.show": {
    en: "Show tooltip",
    da: "Vis værktøjstip",
    de: "Tooltip anzeigen",
    es: "Mostrar información sobre herramientas",
    fr: "Afficher l'infobulle",
    he: "הצג תיאור כלי",
    hr: "Prikaži opis alata",
    it: "Mostra suggerimento",
    ja: "ツールチップを表示",
    "ko-KR": "툴팁 표시",
    no: "Vis verktøytips",
    pl: "Pokaż podpowiedź",
    pt: "Mostrar dica de ferramenta",
    "pt-BR": "Mostrar dica de ferramenta",
    ru: "Показать подсказку",
    sr: "Prikaži opis alata",
    tr: "Araç ipucunu göster",
    uk: "Показати підказку",
    "zh-CN": "显示工具提示",
    "zh-TW": "顯示工具提示",
  },

  // Error
  "error.title": {
    en: "Error Loading Data",
    da: "Fejl ved indlæsning af data",
    de: "Fehler beim Laden der Daten",
    es: "Error al cargar datos",
    fr: "Erreur lors du chargement des données",
    he: "שגיאה בטעינת נתונים",
    hr: "Greška pri učitavanju podataka",
    it: "Errore nel caricamento dei dati",
    ja: "データの読み込みエラー",
    "ko-KR": "데이터 로드 오류",
    no: "Feil ved lasting av data",
    pl: "Błąd ładowania danych",
    pt: "Erro ao carregar dados",
    "pt-BR": "Erro ao carregar dados",
    ru: "Ошибка загрузки данных",
    sr: "Greška pri učitavanju podataka",
    tr: "Veri yükleme hatası",
    uk: "Помилка завантаження даних",
    "zh-CN": "加载数据出错",
    "zh-TW": "加載資料出錯",
  },
  "error.retry": {
    en: "Retry",
    da: "Prøv igen",
    de: "Erneut versuchen",
    es: "Reintentar",
    fr: "Réessayer",
    he: "נסה שוב",
    hr: "Pokušaj ponovo",
    it: "Riprova",
    ja: "再試行",
    "ko-KR": "다시 시도",
    no: "Prøv på nytt",
    pl: "Spróbuj ponownie",
    pt: "Tentar novamente",
    "pt-BR": "Tentar novamente",
    ru: "Повторить попытку",
    sr: "Pokušaj ponovo",
    tr: "Tekrar dene",
    uk: "Спробувати ще раз",
    "zh-CN": "重试",
    "zh-TW": "重試",
  },
  "error.copied": {
    en: "Copied!",
    da: "Kopieret!",
    de: "Kopiert!",
    es: "¡Copiado!",
    fr: "Copié !",
    he: "הועתק!",
    hr: "Kopirano!",
    it: "Copiato!",
    ja: "コピーしました！",
    "ko-KR": "복사됨!",
    no: "Kopiert!",
    pl: "Skopiowano!",
    pt: "Copiado!",
    "pt-BR": "Copiado!",
    ru: "Скопировано!",
    sr: "Kopirano!",
    tr: "Kopyalandı!",
    uk: "Скопійовано!",
    "zh-CN": "已复制！",
    "zh-TW": "已複製！",
  },
  "error.copyDetails": {
    en: "Copy Error Details",
    da: "Kopiér fejldetaljer",
    de: "Fehlerdetails kopieren",
    es: "Copiar detalles del error",
    fr: "Copier les détails de l'erreur",
    he: "העתק פרטי שגיאה",
    hr: "Kopiraj detalje greške",
    it: "Copia dettagli errore",
    ja: "エラー詳細をコピー",
    "ko-KR": "오류 세부정보 복사",
    no: "Kopier feildetaljer",
    pl: "Kopiuj szczegóły błędu",
    pt: "Copiar detalhes do erro",
    "pt-BR": "Copiar detalhes do erro",
    ru: "Копировать детали ошибки",
    sr: "Kopiraj detalje greške",
    tr: "Hata ayrıntılarını kopyala",
    uk: "Скопіювати деталі помилки",
    "zh-CN": "复制错误详情",
    "zh-TW": "複製錯誤詳情",
  },

  // Loading
  "loading.message": {
    en: "Loading Arc Raiders data...",
    da: "Indlæser Arc Raiders-data...",
    de: "Lade Arc Raiders-Daten...",
    es: "Cargando datos de Arc Raiders...",
    fr: "Chargement des données Arc Raiders...",
    he: "טוען נתוני Arc Raiders...",
    hr: "Učitavanje podataka Arc Raiders...",
    it: "Caricamento dati Arc Raiders...",
    ja: "Arc Raidersデータを読み込み中...",
    "ko-KR": "Arc Raiders 데이터 불러오는 중...",
    no: "Laster inn Arc Raiders-data...",
    pl: "Ładowanie danych Arc Raiders...",
    pt: "Carregando dados do Arc Raiders...",
    "pt-BR": "Carregando dados do Arc Raiders...",
    ru: "Загрузка данных Arc Raiders...",
    sr: "Učitavanje podataka Arc Raiders...",
    tr: "Arc Raiders verileri yükleniyor...",
    uk: "Завантаження даних Arc Raiders...",
    "zh-CN": "正在加载Arc Raiders数据...",
    "zh-TW": "正在加載Arc Raiders資料...",
  },

  // Requirement
  "requirement.lvl": {
    en: "Lvl",
    da: "Niv.",
    de: "Stufe",
    es: "Niv.",
    fr: "Niv.",
    he: "דרג.",
    hr: "Raz.",
    it: "Liv.",
    ja: "レベル",
    "ko-KR": "레벨",
    no: "Nivå",
    pl: "Poziom",
    pt: "Nível",
    "pt-BR": "Nível",
    ru: "Ур.",
    sr: "Niv.",
    tr: "Seviye",
    uk: "Рів.",
    "zh-CN": "等级",
    "zh-TW": "等級",
  },
  "requirement.quest": {
    en: "Quest",
    da: "Quest",
    de: "Quest",
    es: "Misión",
    fr: "Quête",
    he: "משימה",
    hr: "Zadatak",
    it: "Missione",
    ja: "クエスト",
    "ko-KR": "퀘스트",
    no: "Oppdrag",
    pl: "Zadanie",
    pt: "Missão",
    "pt-BR": "Missão",
    ru: "Задание",
    sr: "Zadatak",
    tr: "Görev",
    uk: "Завдання",
    "zh-CN": "任务",
    "zh-TW": "任務",
  },
  "requirement.step": {
    en: "Step",
    da: "Trin",
    de: "Schritt",
    es: "Paso",
    fr: "Étape",
    he: "שלב",
    hr: "Korak",
    it: "Passo",
    ja: "ステップ",
    "ko-KR": "단계",
    no: "Steg",
    pl: "Krok",
    pt: "Etapa",
    "pt-BR": "Etapa",
    ru: "Шаг",
    sr: "Korak",
    tr: "Adım",
    uk: "Крок",
    "zh-CN": "步骤",
    "zh-TW": "步驟",
  },

  // ── Category filter options ──────────────────────────────────────────

  "category.ammunition": {
    en: "Ammunition",
    da: "Ammunition",
    de: "Munition",
    es: "Munición",
    fr: "Munitions",
    he: "תחמושת",
    hr: "Municija",
    it: "Munizioni",
    ja: "弾薬",
    "ko-KR": "탄약",
    no: "Ammunisjon",
    pl: "Amunicja",
    pt: "Munição",
    "pt-BR": "Munição",
    ru: "Боеприпасы",
    sr: "Муниција",
    tr: "Mühimmat",
    uk: "Боєприпаси",
    "zh-CN": "弹药",
    "zh-TW": "彈藥",
  },
  "category.assaultrifle": {
    en: "Assault Rifle",
    da: "Stormriffel",
    de: "Sturmgewehr",
    es: "Rifle de asalto",
    fr: "Fusil d'assaut",
    he: "רובה סער",
    hr: "Jurišna puška",
    it: "Fucile d'assalto",
    ja: "アサルトライフル",
    "ko-KR": "돌격소총",
    no: "Angrepsrifle",
    pl: "Karabin szturmowy",
    pt: "Rifle de assalto",
    "pt-BR": "Rifle de assalto",
    ru: "Штурмовая винтовка",
    sr: "Јуришна пушка",
    tr: "Taarruz tüfeği",
    uk: "Штурмова гвинтівка",
    "zh-CN": "突击步枪",
    "zh-TW": "突擊步槍",
  },
  "category.augment": {
    en: "Augment",
    da: "Augment",
    de: "Augment",
    es: "Aumento",
    fr: "Augment",
    he: "שדרוג",
    hr: "Pojačanje",
    it: "Potenziamento",
    ja: "オーグメント",
    "ko-KR": "오그먼트",
    no: "Augment",
    pl: "Augment",
    pt: "Aumento",
    "pt-BR": "Aumento",
    ru: "Аугмент",
    sr: "Појачање",
    tr: "Güçlendirme",
    uk: "Аугмент",
    "zh-CN": "增益",
    "zh-TW": "增益",
  },
  "category.basicmaterial": {
    en: "Basic Material",
    da: "Basismateriale",
    de: "Grundmaterial",
    es: "Material básico",
    fr: "Matériau de base",
    he: "חומר בסיסי",
    hr: "Osnovni materijal",
    it: "Materiale base",
    ja: "基本素材",
    "ko-KR": "기본 재료",
    no: "Grunnmateriale",
    pl: "Podstawowy materiał",
    pt: "Material básico",
    "pt-BR": "Material básico",
    ru: "Базовый материал",
    sr: "Основни материјал",
    tr: "Temel malzeme",
    uk: "Базовий матеріал",
    "zh-CN": "基础材料",
    "zh-TW": "基礎材料",
  },
  "category.battlerifle": {
    en: "Battle Rifle",
    da: "Kampriffel",
    de: "Kampfgewehr",
    es: "Rifle de combate",
    fr: "Fusil de combat",
    he: "רובה קרב",
    hr: "Borbena puška",
    it: "Fucile da combattimento",
    ja: "バトルライフル",
    "ko-KR": "전투소총",
    no: "Kamprifle",
    pl: "Karabin bojowy",
    pt: "Rifle de combate",
    "pt-BR": "Rifle de combate",
    ru: "Боевая винтовка",
    sr: "Борбена пушка",
    tr: "Muharebe tüfeği",
    uk: "Бойова гвинтівка",
    "zh-CN": "战斗步枪",
    "zh-TW": "戰鬥步槍",
  },
  "category.blueprint": {
    en: "Blueprint",
    da: "Tegning",
    de: "Bauplan",
    es: "Plano",
    fr: "Plan",
    he: "תוכנית",
    hr: "Nacrt",
    it: "Progetto",
    ja: "ブループリント",
    "ko-KR": "설계도",
    no: "Blåkopi",
    pl: "Plan",
    pt: "Planta",
    "pt-BR": "Planta",
    ru: "Чертёж",
    sr: "Нацрт",
    tr: "Taslak",
    uk: "Креслення",
    "zh-CN": "蓝图",
    "zh-TW": "藍圖",
  },
  "category.handcannon": {
    en: "Hand Cannon",
    da: "Håndkanon",
    de: "Handkanone",
    es: "Cañón de mano",
    fr: "Canon à main",
    he: "תותח יד",
    hr: "Ručni top",
    it: "Cannone a mano",
    ja: "ハンドキャノン",
    "ko-KR": "핸드캐논",
    no: "Håndkanon",
    pl: "Ręczna armata",
    pt: "Canhão de mão",
    "pt-BR": "Canhão de mão",
    ru: "Ручная пушка",
    sr: "Ручни топ",
    tr: "El topu",
    uk: "Ручна гармата",
    "zh-CN": "手炮",
    "zh-TW": "手砲",
  },
  "category.key": {
    en: "Key",
    da: "Nøgle",
    de: "Schlüssel",
    es: "Llave",
    fr: "Clé",
    he: "מפתח",
    hr: "Ključ",
    it: "Chiave",
    ja: "キー",
    "ko-KR": "열쇠",
    no: "Nøkkel",
    pl: "Klucz",
    pt: "Chave",
    "pt-BR": "Chave",
    ru: "Ключ",
    sr: "Кључ",
    tr: "Anahtar",
    uk: "Ключ",
    "zh-CN": "钥匙",
    "zh-TW": "鑰匙",
  },
  "category.lmg": {
    en: "LMG",
    da: "LMG",
    de: "LMG",
    es: "LMG",
    fr: "LMG",
    he: "LMG",
    hr: "LMG",
    it: "LMG",
    ja: "ライトマシンガン",
    "ko-KR": "경기관총",
    no: "LMG",
    pl: "LMG",
    pt: "LMG",
    "pt-BR": "LMG",
    ru: "Ручной пулемёт",
    sr: "ЛМГ",
    tr: "LMG",
    uk: "Ручний кулемет",
    "zh-CN": "轻机枪",
    "zh-TW": "輕機槍",
  },
  "category.misc": {
    en: "Misc",
    da: "Diverse",
    de: "Sonstiges",
    es: "Varios",
    fr: "Divers",
    he: "שונות",
    hr: "Razno",
    it: "Varie",
    ja: "その他",
    "ko-KR": "기타",
    no: "Diverse",
    pl: "Różne",
    pt: "Diversos",
    "pt-BR": "Diversos",
    ru: "Разное",
    sr: "Разно",
    tr: "Çeşitli",
    uk: "Різне",
    "zh-CN": "杂项",
    "zh-TW": "雜項",
  },
  "category.modification": {
    en: "Modification",
    da: "Modifikation",
    de: "Modifikation",
    es: "Modificación",
    fr: "Modification",
    he: "שינוי",
    hr: "Modifikacija",
    it: "Modifica",
    ja: "モディフィケーション",
    "ko-KR": "개조",
    no: "Modifikasjon",
    pl: "Modyfikacja",
    pt: "Modificação",
    "pt-BR": "Modificação",
    ru: "Модификация",
    sr: "Модификација",
    tr: "Modifikasyon",
    uk: "Модифікація",
    "zh-CN": "改装",
    "zh-TW": "改裝",
  },
  "category.nature": {
    en: "Nature",
    da: "Natur",
    de: "Natur",
    es: "Naturaleza",
    fr: "Nature",
    he: "טבע",
    hr: "Priroda",
    it: "Natura",
    ja: "自然素材",
    "ko-KR": "자연",
    no: "Natur",
    pl: "Natura",
    pt: "Natureza",
    "pt-BR": "Natureza",
    ru: "Природа",
    sr: "Природа",
    tr: "Doğa",
    uk: "Природа",
    "zh-CN": "自然",
    "zh-TW": "自然",
  },
  "category.pistol": {
    en: "Pistol",
    da: "Pistol",
    de: "Pistole",
    es: "Pistola",
    fr: "Pistolet",
    he: "אקדח",
    hr: "Pištolj",
    it: "Pistola",
    ja: "ピストル",
    "ko-KR": "권총",
    no: "Pistol",
    pl: "Pistolet",
    pt: "Pistola",
    "pt-BR": "Pistola",
    ru: "Пистолет",
    sr: "Пиштољ",
    tr: "Tabanca",
    uk: "Пістолет",
    "zh-CN": "手枪",
    "zh-TW": "手槍",
  },
  "category.quickuse": {
    en: "Quick Use",
    da: "Hurtigbrug",
    de: "Schnellnutzung",
    es: "Uso rápido",
    fr: "Utilisation rapide",
    he: "שימוש מהיר",
    hr: "Brza uporaba",
    it: "Uso rapido",
    ja: "クイックユース",
    "ko-KR": "빠른 사용",
    no: "Hurtigbruk",
    pl: "Szybkie użycie",
    pt: "Uso rápido",
    "pt-BR": "Uso rápido",
    ru: "Быстрое использование",
    sr: "Брза употреба",
    tr: "Hızlı kullanım",
    uk: "Швидке використання",
    "zh-CN": "快速使用",
    "zh-TW": "快速使用",
  },
  "category.recyclable": {
    en: "Recyclable",
    da: "Genanvendeligt",
    de: "Recycelbar",
    es: "Reciclable",
    fr: "Recyclable",
    he: "ניתן למיחזור",
    hr: "Reciklirajuće",
    it: "Riciclabile",
    ja: "リサイクル品",
    "ko-KR": "재활용품",
    no: "Resirkulerbart",
    pl: "Do recyklingu",
    pt: "Reciclável",
    "pt-BR": "Reciclável",
    ru: "Перерабатываемое",
    sr: "Рециклажно",
    tr: "Geri dönüştürülebilir",
    uk: "Переробне",
    "zh-CN": "可回收",
    "zh-TW": "可回收",
  },
  "category.refinedmaterial": {
    en: "Refined Material",
    da: "Raffineret materiale",
    de: "Veredeltes Material",
    es: "Material refinado",
    fr: "Matériau raffiné",
    he: "חומר מעובד",
    hr: "Rafinirani materijal",
    it: "Materiale raffinato",
    ja: "精製素材",
    "ko-KR": "정제 재료",
    no: "Foredlet materiale",
    pl: "Rafinowany materiał",
    pt: "Material refinado",
    "pt-BR": "Material refinado",
    ru: "Очищенный материал",
    sr: "Рафинирани материјал",
    tr: "İşlenmiş malzeme",
    uk: "Очищений матеріал",
    "zh-CN": "精炼材料",
    "zh-TW": "精煉材料",
  },
  "category.smg": {
    en: "SMG",
    da: "SMG",
    de: "MP",
    es: "Subfusil",
    fr: "PM",
    he: "SMG",
    hr: "SMG",
    it: "SMG",
    ja: "サブマシンガン",
    "ko-KR": "기관단총",
    no: "SMG",
    pl: "PM",
    pt: "Submetralhadora",
    "pt-BR": "Submetralhadora",
    ru: "Пистолет-пулемёт",
    sr: "СМГ",
    tr: "SMG",
    uk: "Пістолет-кулемет",
    "zh-CN": "冲锋枪",
    "zh-TW": "衝鋒槍",
  },
  "category.shield": {
    en: "Shield",
    da: "Skjold",
    de: "Schild",
    es: "Escudo",
    fr: "Bouclier",
    he: "מגן",
    hr: "Štit",
    it: "Scudo",
    ja: "シールド",
    "ko-KR": "방패",
    no: "Skjold",
    pl: "Tarcza",
    pt: "Escudo",
    "pt-BR": "Escudo",
    ru: "Щит",
    sr: "Штит",
    tr: "Kalkan",
    uk: "Щит",
    "zh-CN": "护盾",
    "zh-TW": "護盾",
  },
  "category.shotgun": {
    en: "Shotgun",
    da: "Haglgevær",
    de: "Schrotflinte",
    es: "Escopeta",
    fr: "Fusil à pompe",
    he: "רובה ציד",
    hr: "Sačmarica",
    it: "Fucile a pompa",
    ja: "ショットガン",
    "ko-KR": "산탄총",
    no: "Hagle",
    pl: "Strzelba",
    pt: "Espingarda",
    "pt-BR": "Espingarda",
    ru: "Дробовик",
    sr: "Сачмарица",
    tr: "Pompalı tüfek",
    uk: "Дробовик",
    "zh-CN": "霰弹枪",
    "zh-TW": "霰彈槍",
  },
  "category.sniperrifle": {
    en: "Sniper Rifle",
    da: "Sniperriffel",
    de: "Scharfschützengewehr",
    es: "Rifle de francotirador",
    fr: "Fusil de précision",
    he: "רובה צלפים",
    hr: "Snajperska puška",
    it: "Fucile di precisione",
    ja: "スナイパーライフル",
    "ko-KR": "저격소총",
    no: "Snikskytterrifle",
    pl: "Karabin snajperski",
    pt: "Rifle de precisão",
    "pt-BR": "Rifle de precisão",
    ru: "Снайперская винтовка",
    sr: "Снајперска пушка",
    tr: "Keskin nişancı tüfeği",
    uk: "Снайперська гвинтівка",
    "zh-CN": "狙击步枪",
    "zh-TW": "狙擊步槍",
  },
  "category.special": {
    en: "Special",
    da: "Speciel",
    de: "Spezial",
    es: "Especial",
    fr: "Spécial",
    he: "מיוחד",
    hr: "Posebno",
    it: "Speciale",
    ja: "スペシャル",
    "ko-KR": "특수",
    no: "Spesial",
    pl: "Specjalny",
    pt: "Especial",
    "pt-BR": "Especial",
    ru: "Особое",
    sr: "Посебно",
    tr: "Özel",
    uk: "Особливе",
    "zh-CN": "特殊",
    "zh-TW": "特殊",
  },
  "category.topsidematerial": {
    en: "Topside Material",
    da: "Topside-materiale",
    de: "Topside-Material",
    es: "Material de Topside",
    fr: "Matériau de Topside",
    he: "חומר עילי",
    hr: "Topside materijal",
    it: "Materiale Topside",
    ja: "トップサイド素材",
    "ko-KR": "지상 재료",
    no: "Topside-materiale",
    pl: "Materiał Topside",
    pt: "Material de Topside",
    "pt-BR": "Material de Topside",
    ru: "Материал Топсайда",
    sr: "Topside материјал",
    tr: "Topside malzemesi",
    uk: "Матеріал Топсайду",
    "zh-CN": "地表材料",
    "zh-TW": "地表材料",
  },
  "category.trinket": {
    en: "Trinket",
    da: "Tingest",
    de: "Schmuckstück",
    es: "Baratija",
    fr: "Babiole",
    he: "תכשיט",
    hr: "Sitnica",
    it: "Ninnolo",
    ja: "トリンケット",
    "ko-KR": "장신구",
    no: "Smykke",
    pl: "Drobiazg",
    pt: "Bugiganga",
    "pt-BR": "Bugiganga",
    ru: "Безделушка",
    sr: "Ситница",
    tr: "Biblo",
    uk: "Дрібничка",
    "zh-CN": "饰品",
    "zh-TW": "飾品",
  },

  // ── Rarity filter options ────────────────────────────────────────────

  "rarity.common": {
    en: "Common",
    da: "Almindelig",
    de: "Gewöhnlich",
    es: "Común",
    fr: "Commun",
    he: "נפוץ",
    hr: "Obično",
    it: "Comune",
    ja: "コモン",
    "ko-KR": "일반",
    no: "Vanlig",
    pl: "Zwykły",
    pt: "Comum",
    "pt-BR": "Comum",
    ru: "Обычное",
    sr: "Обично",
    tr: "Sıradan",
    uk: "Звичайне",
    "zh-CN": "普通",
    "zh-TW": "普通",
  },
  "rarity.uncommon": {
    en: "Uncommon",
    da: "Ualmindelig",
    de: "Ungewöhnlich",
    es: "Poco común",
    fr: "Peu commun",
    he: "לא נפוץ",
    hr: "Neobično",
    it: "Non comune",
    ja: "アンコモン",
    "ko-KR": "고급",
    no: "Uvanlig",
    pl: "Niepospolity",
    pt: "Incomum",
    "pt-BR": "Incomum",
    ru: "Необычное",
    sr: "Необично",
    tr: "Sıra dışı",
    uk: "Незвичайне",
    "zh-CN": "优秀",
    "zh-TW": "優秀",
  },
  "rarity.rare": {
    en: "Rare",
    da: "Sjælden",
    de: "Selten",
    es: "Raro",
    fr: "Rare",
    he: "נדיר",
    hr: "Rijetko",
    it: "Raro",
    ja: "レア",
    "ko-KR": "희귀",
    no: "Sjelden",
    pl: "Rzadki",
    pt: "Raro",
    "pt-BR": "Raro",
    ru: "Редкое",
    sr: "Ретко",
    tr: "Nadir",
    uk: "Рідкісне",
    "zh-CN": "稀有",
    "zh-TW": "稀有",
  },
  "rarity.epic": {
    en: "Epic",
    da: "Episk",
    de: "Episch",
    es: "Épico",
    fr: "Épique",
    he: "אפי",
    hr: "Epsko",
    it: "Epico",
    ja: "エピック",
    "ko-KR": "영웅",
    no: "Episk",
    pl: "Epicki",
    pt: "Épico",
    "pt-BR": "Épico",
    ru: "Эпическое",
    sr: "Епско",
    tr: "Destansı",
    uk: "Епічне",
    "zh-CN": "史诗",
    "zh-TW": "史詩",
  },
  "rarity.legendary": {
    en: "Legendary",
    da: "Legendarisk",
    de: "Legendär",
    es: "Legendario",
    fr: "Légendaire",
    he: "אגדי",
    hr: "Legendarno",
    it: "Leggendario",
    ja: "レジェンダリー",
    "ko-KR": "전설",
    no: "Legendarisk",
    pl: "Legendarny",
    pt: "Lendário",
    "pt-BR": "Lendário",
    ru: "Легендарное",
    sr: "Легендарно",
    tr: "Efsanevi",
    uk: "Легендарне",
    "zh-CN": "传奇",
    "zh-TW": "傳奇",
  },

  // ── Location filter options ──────────────────────────────────────────

  "location.arc": {
    en: "ARC",
    da: "ARC",
    de: "ARC",
    es: "ARC",
    fr: "ARC",
    he: "ARC",
    hr: "ARC",
    it: "ARC",
    ja: "ARC",
    "ko-KR": "ARC",
    no: "ARC",
    pl: "ARC",
    pt: "ARC",
    "pt-BR": "ARC",
    ru: "ARC",
    sr: "ARC",
    tr: "ARC",
    uk: "ARC",
    "zh-CN": "ARC",
    "zh-TW": "ARC",
  },
  "location.commercial": {
    en: "Commercial",
    da: "Kommerciel",
    de: "Kommerziell",
    es: "Comercial",
    fr: "Commercial",
    he: "מסחרי",
    hr: "Komercijalno",
    it: "Commerciale",
    ja: "商業",
    "ko-KR": "상업",
    no: "Kommersiell",
    pl: "Handlowy",
    pt: "Comercial",
    "pt-BR": "Comercial",
    ru: "Коммерческий",
    sr: "Комерцијално",
    tr: "Ticari",
    uk: "Комерційний",
    "zh-CN": "商业",
    "zh-TW": "商業",
  },
  "location.electrical": {
    en: "Electrical",
    da: "Elektrisk",
    de: "Elektrisch",
    es: "Eléctrico",
    fr: "Électrique",
    he: "חשמלי",
    hr: "Električno",
    it: "Elettrico",
    ja: "電気",
    "ko-KR": "전기",
    no: "Elektrisk",
    pl: "Elektryczny",
    pt: "Elétrico",
    "pt-BR": "Elétrico",
    ru: "Электрический",
    sr: "Електрично",
    tr: "Elektrik",
    uk: "Електричний",
    "zh-CN": "电气",
    "zh-TW": "電氣",
  },
  "location.exodus": {
    en: "Exodus",
    da: "Exodus",
    de: "Exodus",
    es: "Éxodo",
    fr: "Exode",
    he: "אקסודוס",
    hr: "Exodus",
    it: "Esodo",
    ja: "エクソダス",
    "ko-KR": "엑소더스",
    no: "Exodus",
    pl: "Exodus",
    pt: "Êxodo",
    "pt-BR": "Êxodo",
    ru: "Исход",
    sr: "Егзодус",
    tr: "Exodus",
    uk: "Ексодус",
    "zh-CN": "Exodus",
    "zh-TW": "Exodus",
  },
  "location.industrial": {
    en: "Industrial",
    da: "Industriel",
    de: "Industriell",
    es: "Industrial",
    fr: "Industriel",
    he: "תעשייתי",
    hr: "Industrijsko",
    it: "Industriale",
    ja: "工業",
    "ko-KR": "산업",
    no: "Industriell",
    pl: "Przemysłowy",
    pt: "Industrial",
    "pt-BR": "Industrial",
    ru: "Промышленный",
    sr: "Индустријско",
    tr: "Endüstriyel",
    uk: "Промисловий",
    "zh-CN": "工业",
    "zh-TW": "工業",
  },
  "location.mechanical": {
    en: "Mechanical",
    da: "Mekanisk",
    de: "Mechanisch",
    es: "Mecánico",
    fr: "Mécanique",
    he: "מכני",
    hr: "Mehaničko",
    it: "Meccanico",
    ja: "機械",
    "ko-KR": "기계",
    no: "Mekanisk",
    pl: "Mechaniczny",
    pt: "Mecânico",
    "pt-BR": "Mecânico",
    ru: "Механический",
    sr: "Механичко",
    tr: "Mekanik",
    uk: "Механічний",
    "zh-CN": "机械",
    "zh-TW": "機械",
  },
  "location.medical": {
    en: "Medical",
    da: "Medicinsk",
    de: "Medizinisch",
    es: "Médico",
    fr: "Médical",
    he: "רפואי",
    hr: "Medicinsko",
    it: "Medico",
    ja: "医療",
    "ko-KR": "의료",
    no: "Medisinsk",
    pl: "Medyczny",
    pt: "Médico",
    "pt-BR": "Médico",
    ru: "Медицинский",
    sr: "Медицинско",
    tr: "Tıbbi",
    uk: "Медичний",
    "zh-CN": "医疗",
    "zh-TW": "醫療",
  },
  "location.nature": {
    en: "Nature",
    da: "Natur",
    de: "Natur",
    es: "Naturaleza",
    fr: "Nature",
    he: "טבע",
    hr: "Priroda",
    it: "Natura",
    ja: "自然",
    "ko-KR": "자연",
    no: "Natur",
    pl: "Natura",
    pt: "Natureza",
    "pt-BR": "Natureza",
    ru: "Природа",
    sr: "Природа",
    tr: "Doğa",
    uk: "Природа",
    "zh-CN": "自然",
    "zh-TW": "自然",
  },
  "location.oldworld": {
    en: "Old World",
    da: "Gamle verden",
    de: "Alte Welt",
    es: "Viejo mundo",
    fr: "Ancien monde",
    he: "עולם ישן",
    hr: "Stari svijet",
    it: "Vecchio mondo",
    ja: "旧世界",
    "ko-KR": "구세계",
    no: "Gammel verden",
    pl: "Stary świat",
    pt: "Mundo antigo",
    "pt-BR": "Mundo antigo",
    ru: "Старый мир",
    sr: "Стари свет",
    tr: "Eski dünya",
    uk: "Старий світ",
    "zh-CN": "旧世界",
    "zh-TW": "舊世界",
  },
  "location.residential": {
    en: "Residential",
    da: "Beboelse",
    de: "Wohngebiet",
    es: "Residencial",
    fr: "Résidentiel",
    he: "מגורים",
    hr: "Stambeno",
    it: "Residenziale",
    ja: "居住",
    "ko-KR": "주거",
    no: "Bolig",
    pl: "Mieszkalny",
    pt: "Residencial",
    "pt-BR": "Residencial",
    ru: "Жилой",
    sr: "Стамбено",
    tr: "Konut",
    uk: "Житловий",
    "zh-CN": "住宅",
    "zh-TW": "住宅",
  },
  "location.security": {
    en: "Security",
    da: "Sikkerhed",
    de: "Sicherheit",
    es: "Seguridad",
    fr: "Sécurité",
    he: "ביטחון",
    hr: "Sigurnosno",
    it: "Sicurezza",
    ja: "セキュリティ",
    "ko-KR": "보안",
    no: "Sikkerhet",
    pl: "Ochrona",
    pt: "Segurança",
    "pt-BR": "Segurança",
    ru: "Безопасность",
    sr: "Безбедносно",
    tr: "Güvenlik",
    uk: "Безпека",
    "zh-CN": "安保",
    "zh-TW": "安保",
  },
  "location.technological": {
    en: "Technological",
    da: "Teknologisk",
    de: "Technologisch",
    es: "Tecnológico",
    fr: "Technologique",
    he: "טכנולוגי",
    hr: "Tehnološko",
    it: "Tecnologico",
    ja: "テクノロジー",
    "ko-KR": "기술",
    no: "Teknologisk",
    pl: "Technologiczny",
    pt: "Tecnológico",
    "pt-BR": "Tecnológico",
    ru: "Технологический",
    sr: "Технолошко",
    tr: "Teknolojik",
    uk: "Технологічний",
    "zh-CN": "科技",
    "zh-TW": "科技",
  },
  "location.nolocation": {
    en: "No Location",
    da: "Ingen placering",
    de: "Kein Fundort",
    es: "Sin ubicación",
    fr: "Aucun lieu",
    he: "ללא מיקום",
    hr: "Bez lokacije",
    it: "Nessuna posizione",
    ja: "場所なし",
    "ko-KR": "위치 없음",
    no: "Ingen plassering",
    pl: "Brak lokalizacji",
    pt: "Sem localização",
    "pt-BR": "Sem localização",
    ru: "Без локации",
    sr: "Без локације",
    tr: "Konum yok",
    uk: "Без локації",
    "zh-CN": "无位置",
    "zh-TW": "無位置",
  },
};
